### ISSUE TITLE
Log In Error

### ISSUE THREAD

**Issue by Alphonsus411** [djangopackages/djangopackages#1049]
12Refused to apply style from '<URL>' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
jquery.min.js:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
/auth/complete/github/img/logo_squares.png:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
site.js:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
jquery.topbar.min.js:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
jquery.tools.min.js:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
jquery.tablesorter.min.js:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
jquery.rotatingnav.min.js:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()
6Refused to execute script from '<URL>' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
angular.min.js:63  Error: Syntax Error: Token ')' not a primary expression at column 36 of the expression [init_search('', '/api/v4/search/', )] starting at [)].
    at e (https://djangopackages.org/static/angular/angular.min.js:68:150)
    at A (https://djangopackages.org/static/angular/angular.min.js:72:8)
    at v (https://djangopackages.org/static/angular/angular.min.js:71:398)
    at n (https://djangopackages.org/static/angular/angular.min.js:71:264)
    at x (https://djangopackages.org/static/angular/angular.min.js:71:146)
    at y (https://djangopackages.org/static/angular/angular.min.js:71:64)
    at r (https://djangopackages.org/static/angular/angular.min.js:71:1)
    at z (https://djangopackages.org/static/angular/angular.min.js:70:443)
    at o (https://djangopackages.org/static/angular/angular.min.js:70:329)
    at P (https://djangopackages.org/static/angular/angular.min.js:73:248) <body ng-controller="SearchCtrl" ng-init="init_search('', '/api/v4/search/', )" class="ng-scope">
(anonymous) @ angular.min.js:63
/auth/complete/github/img/logo_squares.png:1 
        
        
        Failed to load resource: the server responded with a status of 404 ()

**Comment by ryancheley** [comment]
Hi @Alphonsus411! Thanks for the bug report. Can you provide more details for how you generated these errors. If you have specific steps to reproduce that will be extremely helpful in diagnosing and fixing the problem.

**Comment by jefftriplett** [comment]
Sorry for the login issues. 

I have logged in and out a few times, and it's quite possible either CloudFlare or GitHub's issues last week might have hit at the wrong time. We use one for auth and one for caching our static asset management for the other. It's also possible it was us, but I'm not seeing anything we can recreate today. 

We are happy to re-open this if the issue continues.
